services:
  - type: web
    name: sentiment-review-dashboard
    env: node
    buildCommand: cd Documents/sentiment/review-dashboard && npm install && npm run build
    startCommand: cd Documents/sentiment/review-dashboard && npx serve -s dist -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.16.0