services:
  - type: web
    name: sentiment-review-dashboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 3000
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22.16.0