services:
  - type: web
    name: sentiment-review-dashboard
    env: node
    buildCommand: pwd && ls -la && find . -name "package.json" | head -10
    startCommand: npx serve -s dist -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.16.0