services:
  - type: web
    name: sentiment-review-dashboard
    env: node
    buildCommand: cd Documents/sentiment/review-dashboard && npm install && npm run build && echo "Build complete. Checking dist:" && ls -la dist/ && echo "Dist contents:" && find dist -type f | head -20
    startCommand: cd Documents/sentiment/review-dashboard && ls -la && npx serve -s dist -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.16.0