services:
  # Frontend Service - Static Site
  - type: web
    name: sentiment-review-dashboard
    env: static
    buildCommand: cd Documents/sentiment/review-dashboard && npm install && npm run build
    staticPublishPath: Documents/sentiment/review-dashboard/dist
    buildFilter:
      paths:
      - Documents/sentiment/review-dashboard/**
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: VITE_OPENAI_API_KEY
        sync: false
      - key: VITE_REDDIT_API_ENDPOINT
        value: https://sentiment-review-backend.onrender.com/api/reddit
      - key: VITE_APPLE_API_ENDPOINT
        value: https://sentiment-review-backend.onrender.com/api/apple-reviews
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_API_ENDPOINT
        value: https://sentiment-review-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Service - Node.js
  - type: web
    name: sentiment-review-backend
    env: node
    region: oregon
    buildCommand: cd Documents/sentiment/review-dashboard/backend && npm install
    startCommand: cd Documents/sentiment/review-dashboard/backend && node server-production.js
    buildFilter:
      paths:
      - Documents/sentiment/review-dashboard/backend/**
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      
      # Apple API Credentials
      - key: APPLE_APP1_ID
        value: "893514610"
      - key: APPLE_APP1_NAME
        value: myHyundai with Bluelink
      - key: APPLE_APP2_ID
        value: "867941329"
      - key: APPLE_APP2_NAME
        value: Genesis Intelligent Assistant
      - key: APPLE_ISSUER_ID
        sync: false
      - key: APPLE_KEY_ID
        sync: false
      - key: APPLE_PRIVATE_KEY_BASE64
        sync: false
      
      # Reddit API Credentials
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: ReviewDashboard/1.0.0
      
      # CORS Configuration
      - key: FRONTEND_URL
        value: https://sentiment-review-dashboard.onrender.com
      
      # Redis (optional)
      - key: REDIS_URL
        sync: false
        
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX
        value: "100"
        
      # Database Configuration
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true