name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Render
      run: |
        echo "Deployment triggered by push to main branch"
        echo "Render.com will automatically detect this push and deploy both services"
        echo "Frontend: sentiment-review-dashboard"
        echo "Backend: sentiment-review-backend"
        echo "Check deployment status at: https://dashboard.render.com"